### ISSUE TITLE
unexpected value at params[:tags][0]["Tier"] when trying to remove existing tags

### ISSUE THREAD

**Issue by jorhett** [opscode-cookbooks/aws#144]
An attempt to remove an existing tag with the tag's explicit value fails:

```ruby
  * aws_resource_tag[i-0e4f5d02] action remove
================================================================================
Error executing action `remove` on resource 'aws_resource_tag[i-0e4f5d02]'
================================================================================

ArgumentError
-------------
unexpected value at params[:tags][0]["Tier"]

Cookbook Trace:
---------------
/var/chef/cache/cookbooks/aws/providers/resource_tag.rb:54:in `block (3 levels) in class_from_file'
/var/chef/cache/cookbooks/aws/providers/resource_tag.rb:53:in `block (2 levels) in class_from_file'
/var/chef/cache/cookbooks/aws/providers/resource_tag.rb:51:in `each'
/var/chef/cache/cookbooks/aws/providers/resource_tag.rb:51:in `block in class_from_file'

Compiled Resource:
------------------
# Declared in /var/chef/cache/cookbooks/jorhett/recipes/tags.rb:47:in `block in from_file'

aws_resource_tag("i-0e445d02") do
  action [:remove]
  retries 0
  retry_delay 2
  cookbook_name "jorhett"
  recipe_name "tags"
  tags {"Tier"=>"front"}
  not_if { #code block }
end
```

**Comment by MarcFletcher** [comment]
+1

**Comment by jas0nfl0yd** [comment]
2 years later...
